eureka:
  server:
    addres:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: discovery

server:
  port: 8761
  address: 0.0.0.0