server:
  port: 8222
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students
            uri: http://student:8090
            predicates:
              - Path=/students/v3/api-docs,/api/v1/students/**
          - id: schools
            uri: http://school:8070
            predicates:
              - Path=/schools/v3/api-docs,/api/v1/schools/**

openapi:
  service:
    title: Gateway service doc
    version: 1.0.0
    url: http://gateway:8222

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /students/v3/api-docs
        name: Students
      - url: /schools/v3/api-docs
        name: School
    enabled: true
    disable-swagger-default-url: true
    path: /swagger-ui.html
