eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8070
  servlet:
    context-path: /

spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/schools
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://student:8090/api/v1/students

kafka:
  bootstrap-servers: kafka:9092

logstash:
  servers: logstash:5001

openapi:
  service:
    title: schools service doc
    version: 1.0.0
    url: http://gateway:8222

springdoc:
  api-docs:
    path: /schools/v3/api-docs
  swagger-ui:
    path: /schools/swagger-ui.html