eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/students
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: kafka:9092

logstash:
  servers: logstash:5001

openapi:
  service:
    title: students service doc
    version: 1.0.0
    url: http://gateway:8222

springdoc:
  api-docs:
    path: /students/v3/api-docs
  swagger-ui:
    path: /students/swagger-ui.html